name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.4.23'

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
